name: Nightly Build

on:
  push:
    branches: [main]
  release:
    types:
      - created

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Creating config
      run: |
        printf '%q' "${{ secrets.TEST_CONFIG }}" > dist/config.json
        printf '%q' "${{ secrets.TEST_CONFIG }}" > dist/pkg/config.json

    - name: Run tests
      run: pnpm test

    - name: Remove config
      if: always()
      run: |
          rm dist/config.json
          rm dist/pkg/config.json

    - name: Upload assets
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 7

    - name: Upload release assets
      if: github.event_name == 'release'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" dist/pkg/freepbx-aws-polly-x64
        gh release upload "${{ github.event.release.tag_name }}" dist/pkg/freepbx-aws-polly-arm64
