name: Build and Upload

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 7
      if: always()

    - name: Upload Release Asset arm64
      uses: actions/upload-release-asset@v1.0.1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/pkg/freepbx-aws-polly-arm64
        asset_name: freepbx-aws-polly-arm64
        asset_content_type: application/octet-stream
      if: github.event_name == 'release' && contains(github.event.release.tag_name, 'v')

    - name: Upload Release Asset x64
      uses: actions/upload-release-asset@v1.0.1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/pkg/freepbx-aws-polly-x64
        asset_name: freepbx-aws-polly-x64
        asset_content_type: application/octet-stream
      if: github.event_name == 'release' && contains(github.event.release.tag_name, 'v')
