name: Nightly Build

on:
  push:
    branches: [main]

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 7
      if: always()
