name: Build and Upload

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 7
      if: always()

    - name: Upload x64 release asset
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/pkg/freepbx-aws-polly-x64
        asset_name: freepbx-aws-polly-x64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload arm64 release asset
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/pkg/freepbx-aws-polly-arm64
        asset_name: freepbx-aws-polly-arm64
        tag: ${{ github.ref }}
        overwrite: true
