name: Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Upload assets
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" dist/pkg/freepbx-aws-polly-x64
        gh release upload "${{ github.event.release.tag_name }}" dist/pkg/freepbx-aws-polly-arm64
